services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/urlshort
      REDIS_URL: redis://redis:6379/0

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: url_postgres
      POSTGRES_DB: urlshort
    volumes:
      - dbdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  dbdata:
